### ISSUE TITLE
generalize cost function 

### ISSUE THREAD

**Issue by 2860166** [pymanopt/pymanopt#109]
how to generalize the cost function? I need to generalize the cost function so that the it compute the objective against a random batch of data. in other words, instead of a constant cost function which only take X as an input, I need to generalize my optimization problem so that it considers different batches of data and labels (in classification problem).
for instance:
```
cost (x, batch1, label1)
cost (x, batch2, label2)
...
```
I appreciate in advance

**Comment by sweichwald** [comment]
Hey @2860166 – a solution may also be something along the following lines:
https://github.com/pymanopt/pymanopt/blob/03d97cae3f685f73e39092cc7bcd360bf822413b/examples/linreg_multiple_autograd.py
or
``` python
# set up
# * cost (referring to X, y)
# * problem
# * and solver with desired maxiter per batch
# then
for X, y in batches:
    w = solver.solve(problem, x=w)
```
