### ISSUE TITLE
Increasing max_iteration in Conjugate Gradient Solver

### ISSUE THREAD

**Issue by Not-IITian** [pymanopt/pymanopt#110]
Hi,

By default, oit is set to 1000. What parameter should i pass in solver class to increase it to some other value?

Thank you

**Comment by kellertuer** [comment]
Scrolling down to “Solvers” in the documentation https://www.pymanopt.org
it should be `maxiter=1000`, so passing that with a larger value should work.

**Comment by Not-IITian** [comment]
Thank you for quick reply. It works indeed.
