### ISSUE TITLE
manifolds mismatch

### ISSUE THREAD

**Issue by jhu-gh** [pymanopt/pymanopt#118]
Hello. 

I noticed there is a file mismatch between the pymanopt I installed using pip, and the current master branch.

From pypi, it's still manifolds/rotations.py whereas it's  manifolds/special_orthogonal_group.py in the current master branch.

in case others have the same issue.

**Comment by nkoep** [comment]
We are (still) in the process of cleaning up and reorganizing things in the toolbox, but renaming a module probably shouldn't have happened without bumping the major version number. Apologies for any inconveniences :pray:
