### ISSUE TITLE
Inner product in psd manifold is missing a "multitransp"

### ISSUE THREAD

**Issue by semlen** [pymanopt/pymanopt#128]
Hi everyone,

first thank you for the great pymanopt package!!

I am currently optimizing on the psd manifold and I found a mismatch regarding the inner product implemented. I think it does not exactly compute the inner product stated in literature, tr(x^-1 u x^-1 v) = tr(u x^-1 v x^-1). (see e.g. http://www.unige.ch/math/vandereycken/papers/published_JeurisVV_2012.pdf, (4.3)

np.tensordot computes the sum of the Hadamard product of (x^-1u) and (x^-1v), but this is equal to sum(tr (x^-1 u x^-1 v)) only if (x^-1v) commutes. Although x and v are symm. it does i.g. not hold for their product... So, the second part should be transposed in line 63:np.tensordot(la.solve(x, u),multitransp(la.solve(x, v)), axes=x.ndim).

**Comment by semlen** [comment]
see this small example, where it doesn't commute:

from pymanopt.manifolds import PositiveDefinite
from pymanopt.tools.multi import multiprod, multitransp
import autograd.numpy as np

K= 3
d=20
np.random.seed(0)

Manifold = PositiveDefinite(20, 3)

x= Manifold.rand()

s1 = Manifold.randvec(x)
s2 = Manifold.randvec(x)

inner_pymanopt = Manifold.inner(x, s1, s2)

def multitrace(A):
    return np.trace(A, axis1=1, axis2=2)

inner_trace = np.sum(multitrace(multiprod(np.linalg.solve(x,s1), np.linalg.solve(x,s2))))

print(inner_pymanopt,np.tensordot(np.linalg.solve(x,s1), multitransp(np.linalg.solve(x,s2)), axes = 3), inner_trace)

**Comment by sweichwald** [comment]
Hi – thanks for pointing this out!

For reference: https://github.com/pymanopt/pymanopt/blob/master/pymanopt/manifolds/psd.py#L64

Would you be up for creating a PR for this? That'd be great :sunglasses:
