### ISSUE TITLE
Pytorch integration

### ISSUE THREAD

**Issue by pvnieo** [pymanopt/pymanopt#130]
Hi,

Thanks for the amazing library.

I want to know if there is a pymanopt pytorch integration planned, and if so, when?
I'm interested in contributing.

Thanks in advance!

**Comment by sweichwald** [comment]
Hi!
Good news: you may want to check out https://github.com/pymanopt/pymanopt/blob/master/examples/multiple_linear_regression.py to see the pytorch backend in action ;-)
Bad news: We are running behind big times with updating the website/documentation – contributions are very welcome (though may take a while for us to triage – sorry!). While we eventually wish to do a complete overhaul to the websites I think PRs to here are most welcome https://github.com/pymanopt/pymanopt.github.io :-)

**Comment by pvnieo** [comment]
Hi,

Thanks for your response! I'll try to take a look to the doc!
Closing the issue!

**Comment by pvnieo** [comment]
Hi @sweichwald 
I'm reopening the issue again!
In fact, the new pytorch backend is not supported in the actual released version!
How to install the last version?

**Comment by pvnieo** [comment]
I just want to mention that in the current released version, pytorch backend is not available!
To use it, one need to install the master version:
```bash
pip3 install git+https://github.com/pymanopt/pymanopt.git@master --upgrade
```
