### ISSUE TITLE
Drop theano support

### ISSUE THREAD

**Issue by nkoep** [pymanopt/pymanopt#149]
While theano seems to have been forked recently by the PyMC folks (see https://github.com/aesara-devs/aesara), I want to discuss the idea of dropping theano support in 0.3.0. Given the direction that deep learning libraries have moved in over the years, I believe it is clear that tape-based (or tracing) autodiff backends are favored by most frameworks due to their much higher flexibility and user friendliness.

At this point supporting theano as the only graph-based autodiff backend left feels like technical debt that we may as well get rid of altogether. This would also allow us to slightly simplify our backend code.

**Comment by NicolasBoumal** [comment]
I'm also in favor of this type of simplifications to the core of the toolbox.

I wasn't able to find out if JAX is tape-based, graph-based or something else (there's a quite helpful [documentation page](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#how-it-s-made-two-foundational-autodiff-functions) about AD in JAX, but I didn't find the answer in there). At any rate, if it's possible to keep the door open to adding JAX support I think that would be useful.

**Comment by nkoep** [comment]
I'm not sure whether there is a technical difference between autograd/jax's system of boxed types and tape-based systems, but I believe it's mostly semantic. The user experience is pretty much the same. And since we already support autograd (jax's predecessor), dropping theano would absolutely still keep the door open for jax.

**Comment by nkoep** [comment]
Theano support was dropped after merging #155.
