### ISSUE TITLE
cost function decorator: module 'pymanopt' has no attribute 'function'

### ISSUE THREAD

**Issue by ivanightingale** [pymanopt/pymanopt#163]
## Release
PyPI stable (0.2.5)

## Python version
3.7.11

## Problem Description
When executing the definition of a cost function, such as
```
@pymanopt.function.Autograd(manifold)
def cost(point):
    return -point @ matrix @ point
```
the following error occurs: `AttributeError: module 'pymanopt' has no attribute 'function'`

### Reproducing the problem
Running any example (such as the [Quickstart example](https://pymanopt.org/docs/latest/quickstart.html)).

### Traceback (from the  [Quickstart example](https://pymanopt.org/docs/latest/quickstart.html))
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-5f42f82dca13> in <module>
     12 matrix = 0.5 * (matrix + matrix.T)
     13 
---> 14 @pymanopt.function.Autograd(manifold)
     15 def cost(point):
     16     return -point @ matrix @ point

AttributeError: module 'pymanopt' has no attribute 'function'
```

**Comment by ivanightingale** [comment]
A different error is raised for the PyPI pre-release version 0.2.6rc1:
```
ValueError                                Traceback (most recent call last)
<ipython-input-2-5f42f82dca13> in <module>
     12 matrix = 0.5 * (matrix + matrix.T)
     13 
---> 14 @pymanopt.function.Autograd(manifold)
     15 def cost(point):
     16     return -point @ matrix @ point

~/.../lib/python3.7/site-packages/pymanopt/autodiff/__init__.py in decorator(*args, **kwargs)
     81 
     82         if len(args) != 0:
---> 83             raise ValueError("Only keyword arguments allowed")
     84 
     85         def inner(function):

ValueError: Only keyword arguments allowed
```

**Comment by nkoep** [comment]
Unfortunately, the documentation is way ahead of 0.2.5. The new API to decorate functions currently only works on master. I'll try my best to find time to add the remaining changes we planned before releasing 1.0.0.

**Comment by ivanightingale** [comment]
> A different error is raised when using the latest PyPI pre-release version 0.2.6rc1:
> 
> ```
> ValueError                                Traceback (most recent call last)
> <ipython-input-2-5f42f82dca13> in <module>
>      12 matrix = 0.5 * (matrix + matrix.T)
>      13 
> ---> 14 @pymanopt.function.Autograd(manifold)
>      15 def cost(point):
>      16     return -point @ matrix @ point
> 
> ~/.../lib/python3.7/site-packages/pymanopt/autodiff/__init__.py in decorator(*args, **kwargs)
>      81 
>      82         if len(args) != 0:
> ---> 83             raise ValueError("Only keyword arguments allowed")
>      84 
>      85         def inner(function):
> 
> ValueError: Only keyword arguments allowed
> ```

I think this earlier problem may have been solved by replacing `Autograd` with `autograd`.

**Comment by nkoep** [comment]
Yep, in that version you didn't have to provide the manifold to the
function decorator yet. This was a recent change on master which is already
reflected in the documentation. So it should work if you use

```python
@pymanopt.function.Autograd
def cost(x):
   ...
```

**Comment by nkoep** [comment]
This issue should be solved now by installing the latest version of pymanopt from pypi. Feel free to open the issue again though if you run into any trouble.
