### ISSUE TITLE
[Trust Regions Solver] IndexError: invalid index to scalar variable

### ISSUE THREAD

**Issue by captain-pool** [pymanopt/pymanopt#164]
Trust Regions Solver throws an error here with `use_rand=True`:
https://github.com/pymanopt/pymanopt/blob/df94ab9e03b5fa3041668defe995d93b8715a6d7/pymanopt/solvers/trust_regions.py#L180-L184

Was it supposed to be:
```python
 eta = 1e-6 * man.randvec(x) 
 # Must be inside trust region 
 while man.norm(x, eta) > Delta: 
     eta = np.sqrt(np.sqrt(np.spacing(1))) * man.randvec(x)
```

**Comment by NicolasBoumal** [comment]
There was indeed a bug; the fix should rather be:

`eta = np.sqrt(np.sqrt(np.spacing(1))) * eta`

The logic is that if eta is too large (as a tangent vector at x), then we make it smaller until it's small enough.

**Comment by captain-pool** [comment]
fixing the PR.
