### ISSUE TITLE
No module named 'pymanopt.optimizers'

### ISSUE THREAD

**Issue by spencerkraisler** [pymanopt/pymanopt#178]
Hello,

I used pip to install Pymanopt. Importing Pymanopt works just fine. But importing Pymanopt.opertimizers leads to the error in the title. Any idea?

I am running the simple example from the documentation: 

```
import autograd.numpy as anp
import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers

anp.random.seed(42)

dim = 3
manifold = pymanopt.manifolds.Sphere(dim)

matrix = anp.random.normal(size=(dim, dim))
matrix = 0.5 * (matrix + matrix.T)

@pymanopt.function.autograd(manifold)
def cost(point):
    return -point @ matrix @ point

problem = pymanopt.Problem(manifold, cost)

optimizer = pymanopt.optimizers.SteepestDescent()
result = optimizer.run(problem)

eigenvalues, eigenvectors = anp.linalg.eig(matrix)
dominant_eigenvector = eigenvectors[:, eigenvalues.argmax()]

print("Dominant eigenvector:", dominant_eigenvector)
print("Pymanopt solution:", result.point)
```

**Comment by NicolasBoumal** [comment]
Hello,
The documentation usually tracks the GitHub version of the code, which has recently changed quite a bit compared to the latest release. Can you install PyManopt from the latest version available on github and try the same code?

**Comment by nkoep** [comment]
As Nicolas pointed out, this was due to the documentation and the latest version on pypi being out of sync. We've since released a new version on pypi so the issue should be resolved now. Feel free to re-open this issue if it's not though.
