### ISSUE TITLE
How can I get log of optimization

### ISSUE THREAD

**Issue by takaya0** [pymanopt/pymanopt#186]
Hello,

I want to get list of point and function value at the point. of each iterations, [(x_1, f(x_1), (x_2, f(x_2)), ...., (x_n, f(x_n))].
How can I get log of optimizations ?

**Comment by nkoep** [comment]
Hey @takaya0. If you are using the steepest descent or conjugate gradient optimizer, then you can instantiate them with `log_verbosity = 1`, e.g. `optimizer = pymanopt.optimizers.ConjugateGradient(log_verbosity=1)`. In that case the results object's `log` dict (`result = optimizer.run(problem)`) should contain an `iterations` key that has the intermediate points and function values. See https://pymanopt.org/docs/stable/optimizers.html#pymanopt.optimizers.optimizer.OptimizerResult.

**Comment by takaya0** [comment]
Thank you @nkoep 
Your reply is very useful for my research.

**Comment by nkoep** [comment]
Glad to hear it! I'm closing the issue for now, but feel free to re-open it if you run into any issues.
