### ISSUE TITLE
Coding neural network paper using Pymanopt function and PyTorch

### ISSUE THREAD

**Issue by ahariri13** [pymanopt/pymanopt#193]
I have been trying to make a PyTorch version for the code of the paper on "Building Deep Networks on Grassmann Manifolds" by Huang et.al. The code is already available in Tensorflow so it shouldn't be that hard (link to Tensorflow code: [https://github.com/master/tensorflow-riemopt/blob/master/examples/grnet/model.py](https://github.com/master/tensorflow-riemopt/blob/master/examples/grnet/model.py).

My only concern is the part of the code where they define the FRMap in which they use a Grassmannian function from the Tensorflow Riemmanian Optimization package whose code for the Grassmann manifold seems fairly similar to the one in Pymanopt (code available [here](https://github.com/master/tensorflow-riemopt/blob/4814b0c4a8bc74bf98f34ba99440f24ea21ab93b/tensorflow_riemopt/manifolds/grassmannian.py#L8). 

Below is a snippet of their Tensorflow function. Can anyone give me an opinion on how to code the build function they wrote which seems to be "Grassmannian parameter initialization" in PyTorch ? 
![image](https://user-images.githubusercontent.com/51477305/170993384-024fc981-edc7-49aa-a93e-90b9ab15a458.png)

I was thinking it would be something like this using Pymanopt's Grassmann function:

`        grassmannian = Grassmann(output_dim,10)\\
        self.w=torch.nn.Parameter(torch.Tensor(grassmannian.random_point()),requires_grad=True)`

Thank you and best regards !
Ali

**Comment by nkoep** [comment]
Hey Ali, sorry for the late reply. From the code example that you shared the parameter should have shape `(num_proj, input_dim, output_dim)`. Setting aside the potentially misleading names of these parameters, it seems you should initialize your weight parameter as:
```python
grassmannian = Grassmann(output_dim, 10, k=num_proj)
self.w = torch.nn.Parameter(torch.from_numpy(grassmannian.random_point()), requires_grad=True)
```
The parameter `k` can be used to construct a product of `k` copies of the same Grassmannian; points on the manifold (which `random_point()` returns) are then represented as numpy arrays of shape `(k, output_dim, input_dim)`.

**Comment by nkoep** [comment]
I'll close this issue for now since there hasn't been any activity lately. As always, feel free to re-open the issue when you still need help.
