### ISSUE TITLE
Performing optimization on a cartesian product of manifolds

### ISSUE THREAD

**Issue by nithingovindarajan** [pymanopt/pymanopt#204]
Hi all,

I have the following (probably basic) question. I want to minimize a cost function on a cartesian product of manifolds M1 x M2 x ... x Md, where each Mi, in my case, is a Stiefel manifold. I would like to provide my own implementations of the Euclidian gradient (should this gradient implementation be serialized in any way?), but I want to let Pymanopt determine the Riemannien gradient for me. It is not exactly clear how I should proceed to implement this. What is the best way to go about this task?

Thank you

Nithin

**Comment by kellertuer** [comment]
I am not sure about the conversion of gradients, but the manifold you are looking for is

https://pymanopt.org/docs/stable/manifolds.html#module-pymanopt.manifolds.product

**Comment by nkoep** [comment]
Hey, for the product of k Stiefel manifolds, the case is quite simple. You
can simply pass the parameter k as a third argument to the Stiefel class
constructor. A cost function then simply accepts a single array of shape
(k, n, r) [1].

The autodiff backend should be able to work out the gradient/Hessian if
needed. Note that every function you pass to the problem class needs to be
decorated with one of the decorators from the pymanopt.function module [2].
Have a look at some of the examples here we provide [3].

Best,
Niklas

[1]
https://pymanopt.org/docs/stable/manifolds.html#module-pymanopt.manifolds.stiefel
[2] https://pymanopt.org/docs/stable/autodiff.html#module-pymanopt.function
[3] https://github.com/pymanopt/pymanopt/tree/master/examples

**Comment by nkoep** [comment]
Ah gotcha, in that case you'll need to use the `Product` manifold class as @kellertuer pointed out above. Here's a simple example based on the one you provided of what that would look like:

```python
from typing import Sequence

import autograd.numpy as np
from numpy.typing import ArrayLike

import pymanopt
import pymanopt.manifolds
import pymanopt.optimizers


# input parameters
N = [5, 5, 4, 6]
R = [2, 3, 2, 2]
dim = 3

# Define manifold
manifold = pymanopt.manifolds.Product(
    [pymanopt.manifolds.Stiefel(n, r) for n, r in zip(N, R)]
)

A = [np.random.normal(size=(n, r)) for n, r in zip(N, R)]


@pymanopt.function.autograd(manifold)
def cost(*point: Sequence[ArrayLike]) -> float:
    return sum([np.linalg.norm(x - a) ** 2 for x, a in zip(point, A)])


@pymanopt.function.autograd(manifold)
def euclidean_gradient(*point: Sequence[ArrayLike]) -> Sequence[ArrayLike]:
    return [2 * (x - a) for x, a in zip(point, A)]


# solve problem
problem = pymanopt.Problem(
    manifold, cost, euclidean_gradient=euclidean_gradient
)
optimizer = pymanopt.optimizers.SteepestDescent()
result_manual = optimizer.run(problem)

problem = pymanopt.Problem(manifold, cost)
result_autograd = optimizer.run(problem)

print(result_manual.point)
print(result_autograd.point)
```

**Comment by nithingovindarajan** [comment]
Thanks a lot!

**Comment by nkoep** [comment]
I'll close this issue for now. Feel free to re-open it though if you need further help.
