### ISSUE TITLE
Pytorch no longer non-optional requirement?

### ISSUE THREAD

**Issue by martinhanik** [pymanopt/pymanopt#211]
Hi, 
thanks for this nice library! I wondered whether PyTorch really needs to be a non-optional requirement?
Cheers

**Comment by nkoep** [comment]
Hi Martin, thanks for raising this issue. That actually seems to be a
mistake in our setup script. I'll look into it next week to clean this up
in the next release!

**Comment by martinhanik** [comment]
Thank you @nkoep this, would be nice!

**Comment by nkoep** [comment]
This is fixed in pymanopt 2.0.1 that I just released to pypi. Thanks for bringing this to our attention :bow:
