### ISSUE TITLE
Is there a method to initialize the start point?

### ISSUE THREAD

**Issue by qiyang-ustc** [pymanopt/pymanopt#217]
Before 1.0, I just initialize the start point manually. But now, there seems no API to initialize. Is there a method to initialize manually?
For example, if I want to perform optimization on the Steifel manifold, I can choose to start with the identity matrix.

**Comment by nkoep** [comment]
Yes, this is still possible. The starting point can be provided as the
`initial_point` argument of an optimizer's `run` method, see
https://pymanopt.org/docs/stable/optimizers.html#pymanopt.optimizers.optimizer.Optimizer.run
.

**Comment by qiyang-ustc** [comment]
Oh, thank you a ton!!

**Comment by crazyn2** [comment]
Could u provide an example when couples of parameters to optimize and just choose part of them to initialize manually?
