### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymanopt/pymanopt#22]
So I was able to port my (hacky) hand-written numpy code to use pymanopt in under 5 minutes, which gave me GPU (theano) acceleration for free.  I also didn't have to think about `vec(X)`.  Super cool...

**Comment by j-towns** [comment]
Hey Kyle, thanks for the message! It's particularly good to hear since ease of use was really the key motivation for starting this project.

Jamie
