### ISSUE TITLE
JAX support

### ISSUE THREAD

**Issue by qiyang-ustc** [pymanopt/pymanopt#248]
Hi,
      I am working with Manifold Optmization with JAX. I felt the Interface connects pymanopt and JAX is annoying. Will pymanopt can support JAX? It support Autograd instead of its successor--JAX. 

Sincerely,

**Comment by yangarbiter** [comment]
They seem to have jax supported (https://github.com/pymanopt/pymanopt/blob/master/src/pymanopt/function.py). However for some reason, if you install directly from pip (`pip install pymanopt`), that version does not have `pymanopt.function.jax`. I would suggest trying to directly install from the github repository (`pip install --upgrade git+https://github.com/pymanopt/pymanopt.git`).

**Comment by qiyang-ustc** [comment]
Thank you so much,  I just realize there is an update of JAX backend support in the latest version (2.1.2-dev).
