### ISSUE TITLE
Pymanopt installed by pip does not match this GitHub

### ISSUE THREAD

**Issue by spencerkraisler** [pymanopt/pymanopt#249]
Hello,

Apologies if this is not the right place to post this issue. I installed Pymanopt using the usual "pip install Pymanopt" and I found that what was installed does not match the source code here. For instance, special_orthogonal_group.py is a file that was installed, and it seems such a file does not exist in this repo. Is pip using a possibly older version of this?

Best regards,
Spencer

**Comment by kellertuer** [comment]
As far as I can see it was moved between 2.1.1 (current release) and master to https://github.com/pymanopt/pymanopt/blob/master/src/pymanopt/manifolds/group.py? Though the current master is not yet a registered new version it seems.

**Comment by sweichwald** [comment]
Should be fixed now, with version 2.2.0.
