### ISSUE TITLE
Problem with PSDFixedRank?

### ISSUE THREAD

**Issue by plcrodrigues** [pymanopt/pymanopt#29]
Hello, everyone

I'm new to pymanopt and to most of the theory on optimization on manifolds, so I thought that I could start exploring it with a very basic example on **low-rank approximation**. The example is as follows:

I have a positive-definite matrix A with dimension (n,n) and want to find a matrix S, also with dimensions (n,n), but rank k (k < n), that minimizes the distance between S and A. A rather classical result from linear algebra is that, when using Frobenius norm to measure the distance between the two matrices, the analytical solution for my problem would be a matrix S containing only the first k principal components of A, as shown [here](https://en.wikipedia.org/wiki/Low-rank_approximation).

With that said, I made the following script:

```
from pymanopt import Problem
from pymanopt.manifolds import PSDFixedRank
from pymanopt.solvers import TrustRegions, SteepestDescent
from functools import partial

import autograd.numpy as np

def low_rank_eig(M,k):
    w,v = np.linalg.eig(M)        
    idx = w.argsort()[::-1]   
    w = w[idx]
    v = v[:,idx]        
    w[k:] = 0    
    return np.dot(v,np.dot(np.diag(w), v.T))

def generate_random_psd(n):
    A = np.random.randn(n,n)
    A = A+A.T
    w,v = np.linalg.eig(A)
    w = 3+5*np.diag(np.random.rand(n))
    A = np.dot(v,np.dot(w,v.T))
    return A

# 1) Instantiate the manifold    

n = 3 # matrix dimension
k = 2 # rank of the matrices

manifold = PSDFixedRank(n,k)

# 2) define the cost function and its derivatives

def cost(Y,A):
    L = np.power(np.linalg.norm(np.dot(Y,Y.T)-A, ord='fro'),2)
    return L    

def egrad(Y,A):
    return 4*np.dot((np.dot(Y,Y.T)-A),Y)   
    
def ehess(Y,U,A):
    return 4*np.dot(np.dot(Y,U.T)+np.dot(U,Y.T),Y) + 4*np.dot(np.dot(Y,Y.T)-A,U)    
     
# 3) instantiate the problem

A = generate_random_psd(n)

problem = Problem(manifold=manifold, 
                  cost=partial(cost, A=A),
                  egrad=partial(egrad, A=A),
                  ehess=partial(ehess, A=A),
                  verbosity=0)

# 4.1) solve the problem with steepest descent

solver = SteepestDescent()
Y = solver.solve(problem)
S_manopt = np.dot(Y,Y.T)
print 'the solution using pymanopt with SteepestDescent()'
print S_manopt
print 'norm of the difference with SteepestDescent()'
print np.linalg.norm(S_manopt-A,ord='fro')

print ''

# 4.2) solve the problem with trust regions
solver = TrustRegions()
Y = solver.solve(problem)
S_manopt = np.dot(Y,Y.T)
print 'the solution using pymanopt with TrustRegions()'
print S_manopt
print 'norm of the difference with TrustRegions()'
print np.linalg.norm(S_manopt-A,ord='fro')

print ''

# 5) analytical solution

S_analy  = low_rank_eig(A,k)
print 'the analytical solution is'
print S_analy
print 'norm of the difference for the analytical solution'
print np.linalg.norm(S_analy-A,ord='fro') 
```

As you will notice, I calculated the gradient and hessian for the cost function (as in the example [here](http://www.manopt.org/manifold_documentation_symfixedrank.html)) and used them to define my problem.

Well, the issue here is that when I use the SteepestDescent solver, the results given by pymanopt are always equal to the analytical result. However, if I use the TrustRegion solver, sometimes the results are identical, sometimes they are quite different. For example, one output I had was

>the solution using pymanopt with SteepestDescent()
>[[ 11.93574955   1.42908566  -1.4901298 ]
> [  1.42908566   4.24446949   1.03247767]
> [ -1.4901298    1.03247767   0.54600024]]
>norm of the difference with SteepestDescent()
>1.07379788392
>
>the solution using pymanopt with TrustRegions()
>[[ 5.67094791  2.58645784 -0.92951899]
> [ 2.58645784  2.21574769 -0.88285803]
> [-0.92951899 -0.88285803  0.35562263]]
>norm of the difference with TrustRegions()
>7.34109827808
>
>the analytical solution is
>[[ 11.93574961   1.42908568  -1.49012981]
> [  1.42908568   4.24446947   1.03247771]
> [ -1.49012981   1.03247771   0.54600027]]
>norm of the difference for the analytical solution
>1.07379788392

Could anybody help me on that?

PS: I think that for the *proj* function in PSDFixedRank the second input argument for the Lyapunov solver is not right. In Matlab one would give -AS as input, but in Python the Lyapunov equation is defined differently, so in fact it should be +AS. In any case, changing this didn't solve my problem neither.

**Comment by j-towns** [comment]
Hey there, thanks for raising this. I think there must be a bug somewhere and we'll be looking into this. You're right that the output of Matlab's lyap function is different to the scipy one (as it says in the docs). In Python:
```
>>> import numpy as np
>>> from scipy.linalg import solve_lyapunov
>>> solve_lyapunov(np.array([[1]]), np.array([[1]]))
array([[ 0.5]])
```
and in MATLAB:
```
>> lyap(1, 1)

ans =

   -0.5000
```
so we should start by fixing the minus sign as you suggest.

I've also checked the original Manopt example, which gives correct outputs when using the trust regions solver with the same settings of n and k that you used. The Matlab script, including outputting matrices for comparison, is here: [https://gist.github.com/j-towns/46d8d2883282607564d2dcb0f29c19b2](https://gist.github.com/j-towns/46d8d2883282607564d2dcb0f29c19b2).

Pymanopt should behave exactly the same as Manopt, so there must be a bug in `PSDFixedRank` or `TrustRegions` or both.

**Comment by plcrodrigues** [comment]
Thank you very much for your reponse @j-towns ! I've just forked the pymanopt project and will be taking a look at the rest of the code. If I can find the origin for this bug I'll let you know :)

**Comment by sweichwald** [comment]
Hi Pedro -- thanks for raising this issue! We are looking into it.
It would be great if you could let us know your python version and the versions of the installed packages like numpy, scipy, autograd (`pip list`); thanks.
Cheers, Sebastian.

**Comment by j-towns** [comment]
So it seems that the problem only affects Python 2 (for me at least). I have run your example code with the exact same version of pymanopt, numpy and scipy with both Python 2 and Python 3. Python 2 fails to find the right solution ~85% of the time, Python 3 finds the right solution ~100% of the time. Python 2 also runs a lot slower. 

The problem might be due to the difference in integer division in 2 vs 3. In Python 2:
```
>>> 1 / 2
0
```
whereas in Python 3
```
>>> 1 / 2
0.5
```
this difference also exists in numpy and scipy array division.

Not sure exactly where we're doing an integer division but wouldn't be surprised if there is one somewhere which is causing this problem.

**Comment by j-towns** [comment]
OK it looks like it was a problem with integer division. Fixed by https://github.com/pymanopt/pymanopt/commit/b62d634a448ebbd0cef50a4b6597c38c37e66f07.

**Comment by j-towns** [comment]
By the way, you've got some redundant lines of code in your script. Since pymanopt can do differentiation automatically you can remove the gradient and Hessian and it will still work fine:
```diff
def cost(Y,A):
    L = np.power(np.linalg.norm(np.dot(Y,Y.T)-A, ord='fro'),2)
    return L    

-def egrad(Y,A):
-    return 4*np.dot((np.dot(Y,Y.T)-A),Y)   
    
-def ehess(Y,U,A):
-    return 4*np.dot(np.dot(Y,U.T)+np.dot(U,Y.T),Y) + 4*np.dot(np.dot(Y,Y.T)-A,U)    
     
# 3) instantiate the problem

A = generate_random_psd(n)

problem = Problem(manifold=manifold, 
                  cost=partial(cost, A=A),
-                  egrad=partial(egrad, A=A),
-                  ehess=partial(ehess, A=A),
                  verbosity=0)
```

**Comment by plcrodrigues** [comment]
Ah, wow, so in the end it was all about this integer division problem ! Cool, thanks for helping me out and showing that I should probably stop postponing moving to Python 3 :P
