### ISSUE TITLE
Forward Backward Behavior for Optimization

### ISSUE THREAD

**Issue by ssakhavi** [pymanopt/pymanopt#35]
Hi

I wanted to ask that whether the current version has forward-backward behavior in order to implement mini-batch updates of the data.

**Comment by ssakhavi** [comment]
Would it make sense if I do the following 

```
for iter in max_iter:
   x_bach,y_batch= getbatches()
   def cost(w):
      return some_function(w,x_batch,y_batch)
   problem = Problem(manifold=manifold, cost=cost)
   mysolver= solver(maxiter=number)
   if iter==1: 
      wopt = mysolver.solve(problem)
   elsif:
      wopt = mysolver.solve(problem,arg=wopt,)
```

**Comment by nkoep** [comment]
Sorry for never getting back to you on this. Given the age of the issue, I'm closing this for now. Feel free to re-open the issue if needed.
