### ISSUE TITLE
quasi-newton solver

### ISSUE THREAD

**Issue by jdily** [pymanopt/pymanopt#36]
Hi, 
I am wondering if anyone implemented some quasi-newton methods using pymanopt.
Like the Broyden Class method proposed in 
[](http://www.math.fsu.edu/~aluffi/archive/paper488.pdf).
I am quite new to use pymanopt, so far, I am not sure if I need to create a H^{-1} (or B^{-1} using the notation in the paper) in order to do the iterative solve.

thx~

**Comment by nkoep** [comment]
Manopt added a BFGS-type algorithm in version 4.0 which I'm planning to eventually port over to pymanopt. Can't really give you an ETA on it though.

**Comment by nkoep** [comment]
I'm closing this in favor of #81.
