### ISSUE TITLE
Simplex and linear manifold

### ISSUE THREAD

**Issue by rflamary** [pymanopt/pymanopt#37]
Hello,

Thank you again for this awesome toolbox.

During my research I often encounter optimization prolem with positivity, simplex or just linear constraints.

I know that you provide the Euclidean manifold in order to allow for more complex optimization problems but i beleive the toolbox would greatly benefit from the 3 "manifold" above.

Cheers,

Rémi

**Comment by j-towns** [comment]
Hi Rémi, thanks for the message. Do you know about [cvxpy](http://www.cvxpy.org/en/latest/)? I think if you're working on problems with _only_ those types of linear constraints then it should be able to handle them. Or are you working with a combination of linear constraints and the type of constraints Manopt/Pymanopt deals with?

**Comment by j-towns** [comment]
There's also [scipy.minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) which again you may well already be aware of.

**Comment by rflamary** [comment]
Hi I know about those other optimization frameworks and have coded myself some new ones when necessary.  

The reason I proposed this is that you already propose a very interesting product manifold that allow for optimization on matrices and possibly vectors but since you only have euclidean manifold for those, you cannot handle simple constraints. In practice it means that  one have to perform block coordinate desent with you manifold optimization as a step.

If I find time to understand your manifold classes I will do a pull request  to implement and illustrate a fun usage.

**Comment by j-towns** [comment]
Nice, pull requests welcome 👍.
