### ISSUE TITLE
Rotation group

### ISSUE THREAD

**Issue by redzt** [pymanopt/pymanopt#40]
Hi~
I am wondering if there is any manifold implemented like [rotationsfactory(n, k)](http://www.manopt.org/manifold_documentation_rotations.html) in `Manopt`?
Thank you

**Comment by j-towns** [comment]
Hey there, I don't think so currently, but this shouldn't be too difficult to port from Manopt. Pull requests welcome!

**Comment by j-towns** [comment]
Closing since this has now been added, thanks to @tingelst!

**Comment by armarion** [comment]
Is this functionality available in version 2.2.0? How do I implement[rotationsfactory(n, k)?

**Comment by kellertuer** [comment]
From the documentation it seems it is called https://pymanopt.org/docs/stable/manifolds.html#module-pymanopt.manifolds.special_orthogonal_group, so it was probably renamed some time.
