### ISSUE TITLE
using feed_dict within tensorflow

### ISSUE THREAD

**Issue by vinay-jayaram** [pymanopt/pymanopt#44]
I've looked through the code, but I can't figure out a way to use feed_dict in conjunction with pymanopt's solvers (though perhaps my tensorflow knowledge is just not good enough). It's a bit irritating because it forces me to re-generate graph before every call to the solver -- is support for that going to make it into pymanopt?

**Comment by luk-f-a** [comment]
hi @sweichwald, I needed this feature so I added it to my fork. It's not complete (I only implemented it for two solvers and only for tensorflow) but maybe it's useful. If you like the approach I can extend it and submit a PR.

https://github.com/luk-f-a/pymanopt/tree/add_rerun_solver

**Comment by sweichwald** [comment]
Agreed, that should somehow be supported. Thanks for raising and thanks for the proposed fix!
In light a further potential major changes to the autodiff backend (cf. #56), I think for now the proposed workaround is viable. In the long run, it would be preferable to not require the solvers to deal with potential feed_dicts, especially if we add support for further backends which may come with their own additional parameters that one may want to pass. This should be dealt with by the backend.

**Comment by luk-f-a** [comment]
I think you're right, requiring solvers to deal with the feed_dicts is not the best option. What about making .solve() a method of Problem, taking a solver instance as input? In that way, Problem could take the feed_dict, use partial or a closure to produce "clean" cost/grad/hess functions. But I am not sure how that might fit (or not fit) with the changes you plan for the autodiff backend.

**Comment by sweichwald** [comment]
Cross-referencing: https://github.com/pymanopt/pymanopt/pull/67#issuecomment-579113026

**Comment by nkoep** [comment]
Closing this in light of https://github.com/pymanopt/pymanopt/pull/58#issuecomment-580247295.
