### ISSUE TITLE
solve_lyapunov

### ISSUE THREAD

**Issue by catch22** [pymanopt/pymanopt#47]
I am getting an `ImportError: cannot import name 'solve_lyapunov'` when importing pymanopt. I think this function might have been renamed to `solve_continuous_lyapunov` in more recent versions of scipy (see https://docs.scipy.org/doc/scipy/reference/linalg.html).

**Comment by j-towns** [comment]
Fixed via https://github.com/pymanopt/pymanopt/commit/1fd1c6c204ca18161d3b8f5684aeaeda1b7853cd
