### ISSUE TITLE
TrustRegions and ConjugateGradient crashes with Product

### ISSUE THREAD

**Issue by yig** [pymanopt/pymanopt#49]
The following small example crashes with a shape mismatch error.

    import autograd.numpy as np
    
    from pymanopt.manifolds import Grassmann, Euclidean, Product
    from pymanopt import Problem
    from pymanopt.solvers import SteepestDescent, TrustRegions
    
    # (1) Instantiate a manifold
    manifold = Product( ( Euclidean(12), Grassmann(12, 3) ) )
    
    # (2) Define the cost function (here using autograd.numpy)
    def cost(X):
        p,B = X
        return np.linalg.norm( np.dot(B.T,p) )
    
    problem = Problem(manifold=manifold, cost=cost)
    
    # (3) Instantiate a Pymanopt solver
    # solver = SteepestDescent()
    solver = TrustRegions()
    
    # let Pymanopt do the rest
    Xopt = solver.solve(problem)
    print(Xopt)

When I run it, I see:

    $ python3 pymanopt_test_bug.py 
    2018-01-31 02:05:58.569271: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
    Compiling cost function...
    Computing gradient of cost function...
    Computing Hessian of cost function...
    Optimizing...
                                                f: +1.414670e+00   |grad|: 3.776283e+00
    Traceback (most recent call last):
      File "pymanopt_test_bug.py", line 22, in <module>
        Xopt = solver.solve(problem)
      File "/usr/local/lib/python3.6/site-packages/pymanopt/solvers/trust_regions.py", line 172, in solve
        mininner, maxinner)
      File "/usr/local/lib/python3.6/site-packages/pymanopt/solvers/trust_regions.py", line 468, in _truncated_conjugate_gradient
        eta = eta + tau * delta
    ValueError: could not broadcast input array from shape (12,3) into shape (12)

**Comment by yig** [comment]
The same crash occurs when TrustRegions is replaced with ConjugateGradient. It works fine with SteepestDescent.

**Comment by yig** [comment]
The type of `tau` is `numpy.float64`. Changing `eta = eta + tau * delta` to `eta = eta + float(tau) * delta` makes the line work.

**Comment by yig** [comment]
There are a few other lines, too (alpha and beta).

**Comment by yig** [comment]
I created a pull request to fix this issue: https://github.com/pymanopt/pymanopt/pull/50

**Comment by j-towns** [comment]
Hi there, thanks for raising this, and sorry for taking so long to get back to you. I think a (slightly) easier fix might be to just change the order of the multiplication, to ensure that our `_TangentVector`'s __mul__ is called. When I first wrote this code I wasn't aware of the subtleties of how Python decides which __mul__/__rmul__ to use (see https://stackoverflow.com/questions/5181320/under-what-circumstances-are-rmul-called).

Does https://github.com/pymanopt/pymanopt/commit/4b27c73ce313e7806c7a3f4d13a757579bf5195d fix this for you?

**Comment by yig** [comment]
Almost. You also need to swap alpha and delta in trust_regions.py line 491.

Also on trust_regions.py lines 495, 513, and 546.

**Comment by j-towns** [comment]
Why not create a pr? 😉

**Comment by nkoep** [comment]
This issue seems to be a lot more subtle than I initially thought, and I really don't know how to solve it properly. It ultimately seems to be caused by numpy's broadcasting mechanism. The following fails on the last line:
```python
import numpy as np
from pymanopt.manifolds import Grassmann, Euclidean, Product


class TangentVector(list):
    def __mul__(self, other):
        return TangentVector([other * val for val in self])

    def __rmul__(self, other):
        print("rmul")
        return self.__mul__(other)


manifold = Product((Euclidean(12), Grassmann(12, 3)))

X = manifold.rand()
T = manifold.randvec(X)
# Wrap the tangent vector in our condensed class.
T = TangentVector(T)

f_py = 1.2
f_np = np.float64(1.2)

# These work fine:

# 1. invokes our __mul__
T * f_py

# 2. invokes our __rmul__ since python floatS don't know what to do with
# sequences
f_py * T

# 3. same as 1.
T * f_np

# 4. This causes issues cause numpy's float __mul__ is invoked which attempts
# to broadcast. In particular, it seems to inspect the shape of the first
# element (an array with shape (12,)), and substitutes f_np by np.ones(12) *
# f_np. This works fine with the first entry in T, but breaks down on the
# second cause one cannot multiply arrays with shape (12,) and (12,3).
f_np * T
```
If one changes the dimension of the Euclidean manifold to something other than 12, numpy will not attempt to broadcast and instead give up, which causes python to call our `__rmul__` method and all is well.

While changing the order of multiplication so the correct `__mul__` method is invoked fixes the issue @yig raised, it's hardly a good solution. Scalar multiplication is commutative, and I'd really hate for this not to be reflected in our code. It's a guaranteed trap to fall into again and again.

**Comment by nkoep** [comment]
I've just pushed the final set of changes to https://github.com/pymanopt/pymanopt/pull/53 regarding this issue. If you have time, please verify that this fixes the problem for you, @yig. Any additional thoughts on the changes, @j-towns?

**Comment by sweichwald** [comment]
I've just verified that #53 fixes the problem raised by @yig by running the example provided.

**Comment by yig** [comment]
Thanks for looking into this. It's a little hard for me to verify since I'm on a forked repos now. In my branch, we also added an optional callback( x ) function parameter to the solvers for printing or recording extra information after each iteration. Shall I create a pull request for that?
