### ISSUE TITLE
Add support for pytorch

### ISSUE THREAD

**Issue by Orcuslc** [pymanopt/pymanopt#52]
Hi, I noticed that pymanopt only supports autograd/tensorflow/theano backends now. Would you consider adding support for pytorch?

**Comment by nkoep** [comment]
Interesting idea. I have no experience with pytorch (yet) so I can't argue for or against it. I'd certainly be interested in trying it out though. Thanks for the suggestion. I'll play around with it if I have time and will get back to you on this.

**Comment by nkoep** [comment]
Solved after https://github.com/pymanopt/pymanopt/pull/67.

**Comment by AlexanderZeilmann** [comment]
Maybe you want to add put on the pymanopt homepage that you support PyTorch.

A short example (like for Autograd, Theano & Tensorflow) would also be nice.
(I know that there is the [examples folder](https://github.com/pymanopt/pymanopt/tree/master/examples), but I doubt that many people will find this at a first glance.)
