### ISSUE TITLE
Tensorflow backend: memory leak

### ISSUE THREAD

**Issue by luk-f-a** [pymanopt/pymanopt#59]
Hi,

I am working in calculating the distribution of an estimator that includes an optimization step. Therefore I had to run the same problem several thousand times. Before reaching that number I ran out of memory. The reason is most likely that the Tensorflow backend opens a session (without context manager) and never closes the session. 
I would be happy to submit an PR with something along the lines below, but only you agree beforehand since it involves an interface change to the Problem class.
I think one possible solution would be to:
   add  "close" method to the backend (with a matching is_close attribute to keep track) and
   add a "close" method to Problem that closes the backend
   possibly also add a call to backend.close in the __del__ method of Problem (just in case).
In my case, every run increases memory consumption by 300MB, so it's not a small leak, but I guess it depends on the size of the graph and the variables involved.

For now the workaround that worked for me was, after the solve method has been called, to run

```  
    tf.reset_default_graph()
    problem._backend._session.close()
```

Let me know. 

Thanks!

**Comment by nkoep** [comment]
This issue can now be addressed via the method outlined in https://github.com/pymanopt/pymanopt/pull/67#issuecomment-579113026, see also https://github.com/pymanopt/pymanopt/blob/89f143de08a9829b08d6416c9afe7927a6fcf9d7/tests/test_backends/test_tensorflow.py#L142
