### ISSUE TITLE
could you please update a few emamples based on tensorflow

### ISSUE THREAD

**Issue by MrGentleBunny** [pymanopt/pymanopt#61]
as you describe in the page https://pymanopt.github.io/  I can "Use a regular Python function" to define problem
however  when  I try to use my Python function,it go wrong and let me use  tensorflow.  
besides, th code below is the example you define. inface tensorflow ban this kind of definition." X = tf.Variable(tf.placeholder(tf.float32))".

     import tensorflow as tf
     import numpy as np

     X = tf.Variable(tf.placeholder(tf.float32))
     cost = tf.exp(-tf.reduce_sum(tf.square(X)))
     problem = Problem(manifold=manifold, cost=cost, arg=X)

**Comment by GentleCat-miaomiao** [comment]
I try to use   the function ConjugateGradient(). but I can use you correctly
I can't find out the correct type of paremeter for the functin Problem. I hava spend a week on it.
please help me .
def cost_GDA_statistical(W, solStruct):  //cost functio
    n, p = shape(W)
    X = solStruct['X']
    aGraph = solStruct['aGraph']
    dist_func = solStruct['dist_func']

    sigma = solStruct['sigma'] * ones((p,1))
    outCost = 0

    nPoints = max(X.shape)
    for tmpC1 in range(0, nPoints):
        for tmpC2 in range(0, nPoints):
            if(aGraph[tmpC1, tmpC2]):
                tmpCost = local_grad(X[0, tmpC1], X[0, tmpC2], W, sigma,  dist_func)
                outCost = outCost + aGraph[tmpC1, tmpC2] * tmpCost
    return outCost

        W = tf.Variable(tf.eye(n,p,dtype=tf.float64))
        b = tf.Variable(tf.zeros([1, 1],dtype=tf.float64))
        cost = b + cal_Cost(W)

        solver = ConjugateGradient()
        manifold = Grassmann(n, p)
        problem = Problem(manifold = manifold, cost = cost, arg=[W, b])
        Xopt = solver.solve(problem)

**Comment by sweichwald** [comment]
Hi there, we are sorry for not getting back earlier!
Given that the issue was raised some time ago -- please let us know if the problem persists.
In case it does, it would greatly facilitate support if you could provide code for a full minimum working example (including imports statements etc) that we can rerun ourselves. This way it will be easier to identify and resolve the problem. Thanks!

**Comment by nkoep** [comment]
I'm closing this for now due to lack of activity. Please feel free to re-raise the issue if it's still of interest.
