### ISSUE TITLE
Computing karcher mean of a set of points on Grassmann manifold ?

### ISSUE THREAD

**Issue by debasmitdas** [pymanopt/pymanopt#69]
I wanted to know the steps to compute Karcher Mean of a set of points on the Grassmann manifold.

**Comment by sweichwald** [comment]
Hi there, the Nelder-Mead solver requires the Karcher mean to be computed -- is `compute_centroid` (https://github.com/pymanopt/pymanopt/blob/86a21165ae2ae492e04b8e1d910feb93c7dd9ddf/pymanopt/solvers/nelder_mead.py#L14) what you're looking for?
