### ISSUE TITLE
Checkgradient

### ISSUE THREAD

**Issue by sylvchev** [pymanopt/pymanopt#71]
Thank you for your awesome work!
Could it be interesting to have an implementation of a `checkgradient` method, like ManOpt https://www.manopt.org/tutorial.html#tools ?

**Comment by sweichwald** [comment]
Hey there, as far as I remember, some time ago others also raised interest in a feature to check user defined gradients -- so indeed, I think there may be some interest :+1: I guess the only reason we do not have that feature is, that none of us had a usecase for it yet :see_no_evil:
Starting points would be `checkdiff`, `checkgradient`, and `checkhessian`

**Comment by sylvchev** [comment]
Ok, I have some time to submit a PR for this contribution. The main issue is that we need to add a dependency to Matplotlib.

**Comment by nkoep** [comment]
Hey Sylvain,

looking forward to the PR! I really could have used this tool while re-implementing some of the examples and working out gradiens/hvps by hand for the callable backend :laughing: 

I think making matplotlib a hard dependency is a little overkill. I'd prefer something along the lines of what we do for different autodiff backends, i.e.,
```python
try:
    import matplotlib as mpl
except ImportError:
    mpl = None

def checkgradient(...):
    if mpl is None:
        raise RuntimeError("The 'checkgradient' function requires matplotlib")
```

**Comment by NicolasBoumal** [comment]
Hello Sylvain,

I have some notes about checkgradient and checkhessian in my lecture notes about optimization on manifolds: if you e-mail me, I can send you a copy. Maybe this would help.

Best,
Nicolas

**Comment by sylvchev** [comment]
@nkoep This is definitely a good idea! I'll make matplotlib a soft dependency.
@NicolasBoumal  Thanks for you notes.
