### ISSUE TITLE
Versioning, PyPI, and doi

### ISSUE THREAD

**Issue by sweichwald** [pymanopt/pymanopt#74]
As of now we do not have a clear routine for bumping version numbers and deploying releases.
The version on PyPI is 2 years behind https://pypi.org/project/pymanopt/

This shall serve as a starting point to discuss how we best deal with this in the future.

What are your ideas and opinions?

Maybe, relying on travis, the process could be automated, such that when we tag a release on github and the version passes all tests that then automagically the new version is also pushed to PyPI?

When we decide to go that route, it  would also be an idea to make our code citeable
https://guides.github.com/activities/citable-code/
and add contributors as authors of these new version's dois -- what do you think?

**Comment by nkoep** [comment]
Let me start off by apologizing for my complete lack of activity and responsiveness these last months. I'll be defending my thesis at the beginning on June. After that I'm planning to contribute much more again, starting with by getting back to finishing the autodiff backend rewrite!

On topic: I like the idea of triggering updates to PyPI based on tags. At the very least, we might want to start by adding a __version__ string to pymanopt/__init__.py: https://github.com/pymanopt/pymanopt/pull/75.

**Comment by NicolasBoumal** [comment]
I like the idea of citeable code -- I'll read more about it in the link you included.

(I've been teaching a course on Riemannian optimization this semester, and several of my students were more comfortable with Python so they naturally used PyManopt. If one of these students (or anyone else) eventually writes some code that could be a good contribution, if would indeed be nice if they can get some academic credit for it.)

**Comment by kellertuer** [comment]
My plan for Manopt.jl is to establish a roadmap – well first to get in all features required to reach 1.0 – and then establish a further roadmap. When and how I will get DOIs, I haven't decided yet, maybe every not-just-bugfixes-release. Also to give students and other collaborators credit.

**Comment by nkoep** [comment]
I think we covered all of the topics discussed here with the recent migration to github actions. I've also just enabled DOI generation for releases on zenodo. Once we release 0.2.6 we should therefore get a DOI generated automatically :partying_face:
