### ISSUE TITLE
error while loading pymanopt

### ISSUE THREAD

**Issue by pramodkaushik** [pymanopt/pymanopt#77]
In [1]: from pymanopt.manifolds import Rotations                                                                                                                                                          
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f320db4e8a16> in <module>
----> 1 from pymanopt.manifolds import Rotations

~/scratch/python3_tf/lib/python3.5/site-packages/pymanopt/manifolds/__init__.py in <module>
      9 from .product import Product
     10 from .fixed_rank import FixedRankEmbedded
---> 11 from .rotations import Rotations
     12 
     13 __all__ = ["Grassmann", "Sphere", "SphereSubspaceIntersection",

~/scratch/python3_tf/lib/python3.5/site-packages/pymanopt/manifolds/rotations.py in <module>
      8 import numpy.linalg as la
      9 import numpy.random as rnd
---> 10 from scipy.misc import comb
     11 from scipy.linalg import expm, logm
     12 

ImportError: cannot import name 'comb'

**Comment by kellertuer** [comment]
It seems that with the most recent version (see the changelog here https://github.com/scipy/scipy/releases/tag/v1.3.0 ) `comb` was moved to `scipy.special` – are you already an 1.3.0?

**Comment by pramodkaushik** [comment]
Thanks! yes, scipy-1.2.1 does not throw this error.

**Comment by kellertuer** [comment]
Well you could to a PR where you change that line 10 to `import from scope.special importst comb`, but maybe it's also better to carefully check whether this appears also elsewhere in pymanopt (and I haven't done that yet).

**Comment by mihaic** [comment]
I made PR #78. I looked but did not find other errors when using SciPy 1.3.0.
