### ISSUE TITLE
Support for multi-ops in certain matrix manifolds

### ISSUE THREAD

**Issue by calincru** [pymanopt/pymanopt#79]
Some methods in a few matrix manifolds cannot be used with stacked arguments despite the use of `multi*` helpers.  

One problem I identified stems from the use of `numpy.linalg.norm` which does not work the same as the more matrix-specific functions such as `numpy.linalg.cholesky`: the latter can deal with arrays of any shape `(..., N, N)` while the former computes the general tensor norm instead of per-matrix Frobenius norms.  To fix it, the `axis` argument has to be set to `(ndim - 2, ndim - 1)`.

**Comment by calincru** [comment]
Now I realized that it's probably by design like that -- for the case k > 1, not to allow computing pairwise distances faster, for instance.  If that's the case, feel free to close this issue.

**Comment by nkoep** [comment]
That is in fact by design, yes. The argument `k` is (most often) used to refer to the number of elements in a product manifold. Methods like `Manifold.norm` are therefore still expected to produce scalars. Hence why norms and metrics usually use `np.tensordot`.
