### ISSUE TITLE
setting a starting point x0

### ISSUE THREAD

**Issue by katosh** [pymanopt/pymanopt#83]
Is there a way to tell the `SteepestDescent` solver where to start the optimization?

**Comment by nkoep** [comment]
Yes, the `solve` method of every solver accepts a parameter `x` to define
the initial point. Admittedly, it should have been called `x0`, which was a
small design oversight on our part.

**Comment by Not-IITian** [comment]
Hi,

Initializing a matrix variable for optimization over smanifold = Stiefel(k, est_rank) using Conjugate gradient gives a type error. I tried to set x as numpy matrix as well as tensorflow. 

How else should one init a matrix type as x?

Thank you for reply.
