### ISSUE TITLE
Tests failing, possibly Tensorflow 2.0 API breaking

### ISSUE THREAD

**Issue by j-towns** [pymanopt/pymanopt#86]
Travis seems to be failing on master due to errors like this:
```
Traceback (most recent call last):
1439 File "/home/travis/build/pymanopt/pymanopt/tests/test_tensorflow.py", line 240, in setUp
1440 self.backend = TensorflowBackend()
1441 File "/home/travis/build/pymanopt/pymanopt/pymanopt/tools/autodiff/_tensorflow.py", line 20, in __init__
1442 self._session = tf.Session()
1443 AttributeError: 'module' object has no attribute 'Session'
```
I'm not sure but I think this is probably due to the release of Tensorflow 2.0, which might have API breaking changes. We should either update our code to TF 2.0 or pin to 1.x and mention in the docs that we have yet to update.

**Comment by nkoep** [comment]
This was fixed in 518bbc12.

**Comment by oleg-kachan** [comment]
@nkoep isn't that commit just sweeps the problem under the carpet?

**Comment by nkoep** [comment]
The commit fixes the build by restricting the tensorflow version to one we support right now. I intend for us to eventually support both the session and post-session TF API in the future, but for now this fix is good enough in my book.
